from http.server import BaseHTTPRequestHandler, HTTPServer
import json, time
EVENTS=[]
HTML='''<!doctype html><meta charset="utf-8"><title>AetherScreens QA</title><style>body{font:22px system-ui;background:#eef5ff;margin:36px}button,input,textarea{font:24px system-ui;padding:16px}button{background:#166aff;color:white;border:0;border-radius:12px}#scroll{height:240px;overflow:auto;background:white;margin-top:24px}#drag{position:absolute;left:650px;top:140px;background:#00a8a0;color:white;padding:36px;cursor:grab}#ball{position:absolute;top:430px;border-radius:30px;background:#166aff;width:60px;height:60px}#clock{font:28px monospace}#response{position:fixed;right:80px;bottom:40px;width:100px;height:100px;background:#eef5ff}#result{white-space:pre-wrap}h1{margin:0 0 20px}</style><h1>AetherScreens Functional QA</h1><button id="click">Click test: 0</button> <button id="reset">Reset counters</button><p><textarea id="input" placeholder="Keyboard / Unicode / paste test" rows="2" cols="38"></textarea></p><div id="drag">Drag me</div><div id="clock"></div><div id="ball"></div><div id="scroll">'''+''.join('<p>Scroll row '+str(i)+'</p>' for i in range(60))+'''</div><div id="response"></div><pre id="result"></pre><script>const click=document.getElementById("click"),reset=document.getElementById("reset"),input=document.getElementById("input"),scroll=document.getElementById("scroll"),drag=document.getElementById("drag"),clock=document.getElementById("clock"),ball=document.getElementById("ball"),result=document.getElementById("result"),response=document.getElementById("response");let count=0;function log(t,d={}){result.textContent=t+' '+JSON.stringify(d);fetch('/event',{method:'POST',body:JSON.stringify({type:t,data:d,time:performance.now()})})};click.onclick=()=>{click.textContent='Click test: '+(++count);response.style.background=count%2?'#ffe9cc':'#eef5ff';log('click',{count})};reset.onclick=()=>{count=0;log('reset')};input.oninput=()=>log('input',{value:input.value});input.onkeydown=e=>log('key',{key:e.key,code:e.code,meta:e.metaKey,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey});input.onpaste=e=>log('paste',{value:e.clipboardData.getData('text')});document.onmousedown=e=>log("mouse-down",{x:e.clientX,y:e.clientY,button:e.button});document.oncontextmenu=e=>{e.preventDefault();log('right-click',{x:e.clientX,y:e.clientY})};scroll.onscroll=()=>log('scroll',{top:scroll.scrollTop});let down=false;drag.onmousedown=e=>{down=true;log('drag-start')};document.onmouseup=e=>{if(down)log('drag-end',{x:e.clientX,y:e.clientY});down=false};document.onmousemove=e=>{if(down){drag.style.left=e.clientX-50+'px';drag.style.top=e.clientY-30+'px'}};function frame(t){clock.textContent='Animation '+(t/1000).toFixed(3)+' seconds';ball.style.left=(500+350*Math.sin(t/700))+'px';requestAnimationFrame(frame)}requestAnimationFrame(frame);log('ready');</script>'''
class H(BaseHTTPRequestHandler):
 def log_message(self,*a): pass
 def do_GET(self):
  payload=json.dumps(EVENTS).encode() if self.path=='/events' else HTML.encode()
  self.send_response(200);self.send_header('Content-Type','application/json' if self.path=='/events' else 'text/html');self.end_headers();self.wfile.write(payload)
 def do_POST(self):
  event=json.loads(self.rfile.read(int(self.headers.get('Content-Length',0))));event['serverTime']=time.time();EVENTS.append(event);self.send_response(200);self.end_headers()
HTTPServer(('127.0.0.1',8766),H).serve_forever()
