// Appended only to the disposable simulator QA app source by the runner.
// No secret, file path or real account is supplied by the test process.
import CryptoKit
import UIKit

@MainActor
private enum SSHKeyUIFixture {
    static func prepare() throws {
        let environment = ProcessInfo.processInfo.environment
        guard let token = environment["AETHERSCREENS_SSH_KEY_QA_TOKEN"],
              let reference = UUID(uuidString: token) else { return }
        let name = "QA Key Source " + token
        let store = DeviceStore.shared
        let vault = SSHCredentialStore.shared
        let journal = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("ssh-key-qa-owned.json")
        var owned = (try? JSONDecoder().decode([String].self, from: Data(contentsOf: journal))) ?? []
        let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let exportName = "QA-Export-" + token
        if environment["AETHERSCREENS_SSH_KEY_QA_ACTION"] == "verify-export" {
            guard owned.contains(token), let seed = try vault.load(kind: .privateKey, reference: reference) else {
                throw SSHPrivateKey.Failure.missing
            }
            let files = try FileManager.default.contentsOfDirectory(at: documents, includingPropertiesForKeys: nil)
                .filter { [exportName, exportName + ".txt"].contains($0.lastPathComponent) }
            guard files.count == 1, try Data(contentsOf: files[0]) == seed else { throw SSHPrivateKey.Failure.invalid }
            return
        }
        if environment["AETHERSCREENS_SSH_KEY_QA_ACTION"] == "cleanup" {
            let ownedFile = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
                .appendingPathComponent("QA-Key-" + token + ".pem")
            let seed = try vault.load(kind: .privateKey, reference: reference) ?? (try? Data(contentsOf: ownedFile))
            for suffix in ["", ".txt"] {
                let exported = documents.appendingPathComponent(exportName + suffix)
                if FileManager.default.fileExists(atPath: exported.path) { try FileManager.default.removeItem(at: exported) }
            }
            if FileManager.default.fileExists(atPath: ownedFile.path) {
                try FileManager.default.removeItem(at: ownedFile)
            }
            let pasteMarker = journal.deletingLastPathComponent().appendingPathComponent("ssh-library-paste-" + token)
            if FileManager.default.fileExists(atPath: pasteMarker.path), let seed {
                // Only fixture-generated bytes in the disposable QA Keychain group.
                for imported in try vault.references(kind: .privateKey) where imported != reference {
                    guard try vault.load(kind: .privateKey, reference: imported) == seed else { continue }
                    try DeviceListViewModel().removeManagedSSHKey(imported)
                    guard try vault.load(kind: .privateKey, reference: imported) == nil else { throw SSHPrivateKey.Failure.invalid }
                }
                try FileManager.default.removeItem(at: pasteMarker)
            }
            let invalid = "QA invalid private key " + token
            // Only the owned simulator clipboard, with exact generated content.
            if UIPasteboard.general.string == invalid || (seed != nil && UIPasteboard.general.string == String(data: seed!, encoding: .utf8)) {
                UIPasteboard.general.items = []
            }
            for var device in store.devices {
                guard case .privateKey(let id) = device.ssh?.authentication, id == reference else { continue }
                if device.name == name {
                    guard store.deleteDevice(device) else { throw SSHPrivateKey.Failure.invalid }
                } else {
                    device.ssh = nil
                    store.addDevice(device)
                }
            }
            try vault.remove(kind: .privateKey, reference: reference)
            guard try vault.load(kind: .privateKey, reference: reference) == nil else { throw SSHPrivateKey.Failure.invalid }
            owned.removeAll { $0 == token }
            try JSONEncoder().encode(owned).write(to: journal, options: .atomic)
            return
        }
        guard ["seed", "seed-library", "seed-paste", "seed-invalid-paste", "seed-library-paste", "seed-library-file", "seed-encrypted-file"].contains(environment["AETHERSCREENS_SSH_KEY_QA_ACTION"] ?? "") else { return }
        if !owned.contains(token) {
            owned.append(token)
            try JSONEncoder().encode(owned).write(to: journal, options: .atomic)
        }
        guard !store.devices.contains(where: { $0.name == name }) else { return }
        let encryptedImport = environment["AETHERSCREENS_SSH_KEY_QA_ACTION"] == "seed-encrypted-file"
        let secret = encryptedImport ? SSHEncryptedQAData.key! : Data(P256.Signing.PrivateKey().pemRepresentation.utf8)
        let settings = SSHConnectionSettings(server: SSHServerAddress(host: "127.0.0.1")!,
            username: "qa-key-user", authentication: .privateKey(reference))!
        let request = ConnectionRequest(host: "127.0.0.1", name: name, ssh: settings)!
        try vault.save(secret, kind: .privateKey, reference: reference)
        let action = environment["AETHERSCREENS_SSH_KEY_QA_ACTION"]
        if action == "seed-library-paste" || action == "seed-library-file" || encryptedImport {
            try Data().write(to: journal.deletingLastPathComponent().appendingPathComponent("ssh-library-paste-" + token), options: .atomic)
        }
        if !encryptedImport && action != "seed-library" && action != "seed-library-paste" && action != "seed-library-file" { store.addDevice(request.device) }
        if action == "seed-library-file" || encryptedImport {
            let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            try FileManager.default.createDirectory(at: documents, withIntermediateDirectories: true)
            try (encryptedImport ? SSHEncryptedQAData.encrypted! : secret).write(to: documents.appendingPathComponent("QA-Key-" + token + ".pem"), options: .atomic)
        }
        if action == "seed-paste" || action == "seed-invalid-paste" || action == "seed-library-paste" {
            let text = action != "seed-invalid-paste" ? String(decoding: secret, as: UTF8.self) : "QA invalid private key " + token
            UIPasteboard.general.setItems([["public.utf8-plain-text": text]],
                options: [.localOnly: true, .expirationDate: Date().addingTimeInterval(300)])
        }
    }
}
